version: "3"

services:
  arquivei-app:
    container_name: arquivei-app
    build: .docker/docker
    image: arquivei-app
    depends_on:
      - arquivei-mysql
    volumes:
      - ./:/application
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa # map your private ssh key

  arquivei-nginx:
    container_name: arquivei-nginx
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .:/application
      - .docker/log:/var/log/nginx/
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arquivei-app
      - arquivei-mysql

  arquivei-mysql:
    container_name: arquivei-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=arquivei
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
