version: "3"

services:
  arquivei-integration-service-app:
    container_name: arquivei-integration-service-app
    build: .docker/integration-service/docker
    image: arquivei-integration-service-app
    depends_on:
      - arquivei-mysql
    volumes:
      - ./integration-service:/application

  arquivei-integration-service-nginx:
    container_name: arquivei-integration-service-nginx
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./integration-service:/application
      - .docker/integration-service/log:/var/log/nginx/
      - .docker/integration-service/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arquivei-integration-service-app
      - arquivei-mysql

  arquivei-mysql:
    container_name: arquivei-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=arquivei
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
