version: "3"

services:
  arquivei-app:
    container_name: arquivei-app
    build: .docker/docker
    image: arquivei-app
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL="127.0.0.1:8000"
      - DB_DATABASE=arquivei
      - DATABASE=arquivei
      - DB_PASSWORD=root
      - ARQUIVEI_ENDPOINT="https://sandbox-api.arquivei.com.br/"
      - ARQUIVEI_VERSION=v1
      - ARQUIVEI_API_ID=f96ae22f7c5d74fa4d78e764563d52811570588e
      - ARQUIVEI_API_KEY=cc79ee9464257c9e1901703e04ac9f86b0f387c2
    depends_on:
      - arquivei-mysql
    volumes:
      - ./:/application
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa # map your private ssh key

  arquivei-nginx:
    container_name: arquivei-nginx
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .:/application
      - .docker/log:/var/log/nginx/
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - arquivei-app
      - arquivei-mysql

  arquivei-mysql:
    container_name: arquivei-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=arquivei
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
